displayName=Always Hear Drops
author=robisa693
description=Even if game is muted, hear all valuable drop sounds through your system sound.
tags=drops,valuable,untradeable,sound,audio,notification,loot
build=standard
plugins=com.robisa693.alwayshearsdrops.AlwaysHearDropsPlugin
