displayName=Always Hear Drops
author=robisa693
description=Hear valuable/untradeable drop sounds even when Sound Effects volume is muted.
tags=drops,valuable,untradeable,sound,notification,muted,loot,rare,drop,alert,audio
build=standard
plugins=com.robisa693.alwayshearsdrops.AlwaysHearDropsPlugin
