displayName=Always Hear Drops
author=robisa693
description=Even if ingame sounds are off! Hear valuable/untradeable drop notifications. No audio files needed, uses in-game sound IDs.
tags=drops,valuable,untradeable,sound,notification,muted,loot,rare,drop,alert,audio
build=standard
plugins=com.robisa693.alwayshearsdrops.AlwaysHearDropsPlugin
